django_project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import core.urls
import user.urls
from django.conf.urls.static import(
    static, 
)

MEDIA_FILE_PATHS = static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core')),
] + MEDIA_FILE_PATHS

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

django_project/core/urls.py
from django.urls import path 

from . import views 

app_name = 'core'
urlpatterns = [
    path('movies',views.MovieList.as_view(),
    name='MovieList'),
    path('movie/<int:pk>',views.MovieDetail.as_view(),
    name='MovieDetail' ),
    path('movie/<int:movie_id>/vote',
    views.CreateVote.as_view(),
    name='CreateVote' ),
    path('movie/<int:movie_id>/vote/<int:pk>',
    views.UpdateVote.as_view(),
    name='UpdateVote' ),
    path('movie/<int:movie_id>/image/upload',
    views.MovieImageUpload.as_view(),
    name='MovieImageUpload' ),
]

django_project/core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.aggregates import (
    Sum
)
from uuid import uuid4
from django.conf import settings
from django.db import models
from PIL import Image, ImageTk
# Create your models here.

class MovieManager(models.Manager):

    def all_with_related_persons(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writers',  
                                'actors')
        return qs

    def all_with_related_persons_and_score(self):
        qs = self.all_with_related_persons()
        qs = qs.annotate(score=Sum('vote__value'))
        return qs
                          
class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_G, 'R - Restricted'),
    )

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED
    )
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    
    director = models.ForeignKey(
        to='Person',
        on_delete=models.SET_NULL,
        related_name='directed',
        null=True,
        blank=True
    )

    writers = models.ManyToManyField(
        to='Person',
        related_name='writing_credits',
        blank=True
    )

    actors = models.ManyToManyField(
        to='Person',
        through='Role',
        related_name='acting_credits',
        blank=True
    )

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed',
                                   'writing_credits',
                                   'role_set__movie')

class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True,blank=True)

    objects = PersonManager()

    class Meta:
        ordering = ('last_name', 'first_name')

    def __str__(self):
        if self.died:
            return '{}, {} ({}-{})'.format(
                self.last_name,
                self.first_name,
                self.born,
                self.died)
        return '{}, {} ({})'.format(
            self.last_name,
            self.first_name,
            self.born
        )

class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

    class Meta:
        unique_together = ('movie',
                            'person',
                            'name')


class VoteManager(models.Manager):

    def get_vote_or_unsaved_blank_vote(self, movie, user):
        try:
            return Vote.objects.get(
                movie=movie,
                user=user
            )
        except Vote.DoesNotExist:
            return Vote(
                movie=movie,
                user=user
            )

class Vote(models.Model):
    UP = +1
    DOWN = -1
    VALUE_CHOICES = (
        (UP, "👍"),
        (DOWN, "👎"),
    )

    value = models.SmallIntegerField(
        choices = VALUE_CHOICES
    )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    movie = models.ForeignKey(
        Movie,
        on_delete=models.CASCADE
    )
    voted_on = models.DateTimeField(
        auto_now=True
    )
    
    objects = VoteManager()

    class Meta:
        unique_together = ('user', 'movie')

def movie_directory_path_with_uuid(
    instance, filename):
    return '{} {}'.format(
        instance.movie_id, uuid4()
    )

class MovieImage(models.Model):
    image = models.ImageField(
        upload_to=movie_directory_path_with_uuid
    )
    uploaded = models.DateTimeField(
        auto_now_add=True
    )
    movie = models.ForeignKey(
        'Movie', on_delete=models.CASCADE
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
        

    

django_project/core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Vote, Movie, MovieImage

class VoteForm(forms.ModelForm):
    
    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True
    )
    value = forms.ChoiceField(
        label='Vote',
        widget=forms.RadioSelect,
        choices=Vote.VALUE_CHOICES,
    )

    class Meta:
        model = Vote
        fields = ('value', 'user', 'movie')

class MovieImageForm(forms.ModelForm):
    movie = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=Movie.objects.all(),
        disabled=True, 
    )

    user = forms.ModelChoiceField(
        widget=forms.HiddenInput,
        queryset=get_user_model().objects.all(),
        disabled=True
    )
    
    class Meta:
        model = MovieImage
        fields = ('image','user','movie')

django_project/core/views.py
from django.shortcuts import redirect
from .models import Movie, Person, Vote
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView
)
from django.urls import reverse
from .forms import VoteForm, MovieImageForm
from django.contrib.auth.mixins import (
    LoginRequiredMixin
)
from django.core.exceptions import (
    PermissionDenied
)
from . import forms

# Create your views here.

class MovieList(ListView):
    model = Movie

class MovieDetail(DetailView):
    queryset = Movie.objects.all_with_related_persons_and_score()
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['image_form'] = self.movie_image_form()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
           )
            if vote.id:
                vote_form_url = reverse(
                'core:UpdateVote',
                kwargs={
                      'movie_id':vote.movie.id,
                      'pk':vote.id
                })
            else:
                vote_form_url = (
                    reverse(
                        'core:CreateVote',
                        kwargs={
                                'movie_id':self.object.id}

                    )
                )
                vote_form = VoteForm(instance=vote)
                ctx['vote_form'] = vote_form
                ctx['vote_form_url'] = vote_form_url   
             
            return ctx

    def movie_image_form(self):
        if self.request.user.is_authenticated:
            return MovieImageForm()
        return None

class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs[
            'movie_id'
        ]
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id
            }
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk':movie_id})
        return redirect(
            to=movie_detail_url
        )  

class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user
        if vote.user != user:
            raise PermissionDenied(
        'cannot change another users vote'
        )
        
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id
            }
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk':movie_id})
        return redirect(
            to=movie_detail_url
        )  

class MovieImageUpload(LoginRequiredMixin, 
              CreateView):
    form_class = MovieImageForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.kwargs['movie_id']
        return reverse(
            'core:MovieDetail',
            kwargs={
                'pk': movie_id
            }
        )

    def render_to_response(self, context, **response_kwargs):
        movie_id = self.kwargs['movie_id']
        movie_detail_url = reverse(
            'core:MovieDetail',
            kwargs={'pk':movie_id})
        return redirect(
            to=movie_detail_url
        )  

django_project/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<div class="col">
    <h1>{{ object }}</h1>
    <p class='lead'>
        {{ object.plot }}
    </p>
</div>
<ul class="movie-image list-inline">
    {% for i in object.movieimage_set.all %}
      <li
      class="list-inline-item">
      <img src="{{ i.image.url }}" alt="">
      </li>
    {% endfor %}
</ul>
<p>
    Directed by {{ object.director }}
</p>
<p>
    Written by {{ object.writing_credits }}
</p>
<p>
    Starring {{ object.acting_credits }}
</p>

{% endblock %}

{% block sidebar %}
<div>
    This movie is rated:
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
    </span>
</div>

<div>
    <h2>
        Score: {{ object.score|default_if_none:"TBD" }}
    </h2>
</div>

<div>
    {% if vote_form %}
        <form 
        method="post"
        action="{{ vote_form_url }}">
            {% csrf_token %}
            {{ vote_form.as_p }}
            <button
            class="btn btn-primary">
            Vote
            </button>
        </form>
    {% else %}
        <p>Log In to vote for this movie</p>
    {% endif %}
</div>
    {% if image_form %}
    <div>
        <h2>Upload New Image</h2>
        <form method="post"
        enctype="multipart/form-data"
        action="{% url 'core:MovieImageUpload'
        movie_id=object.id %}">
        {% csrf_token %}
        {{ image_form.as_p }}
        <p>
            <button
            class="btn btn-primary">
        Upload</button>
        </p>
        </form>
    </div>
    {% endif %}
{% endblock %}

django_project/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
All the Movies
{% endblock %}

{% block main %}
<ul>
    {% for movie in object_list %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
            {{ movie }}
        </a>
    </li>
    {% endfor %}
</ul>
{% if is_paginated %}
    <nav>
        <ul class='pagination'>
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}
                ?page=1" class="page-link">
                First
                </a>
            </li>
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}
                ?page={{ page_obj.previous_page_number }}"
                class="page-link">
                {{ page_obj.previous_page_number }}
            </a>
            </li>
            {% endif %}
            <li class="page-item active">
                <a href="{% url 'core:MovieList' %}
                ?page={{ page_obj.number }}"
                class="page-link">
            {{ page_obj.number }}
            </a>
            </li>
            {% if page_obj.has_next %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}
                ?page={{ page_obj.next_page_number }}"
                class="page-link">
                {{ page_obj.next_page_number }}
            </a>
            </li>
            {% endif %}
            <li class="page-item">
                <a href="{% url 'core:MovieList' %}
                ?page=last"
                class="page-link">
            Last
            </a>
            </li>
        </ul>
    </nav>
{% endif %}
{% endblock %}

<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
       {% for movie in object_list %}
       <li>{{movie}}</li>
       {% empty %}
       <li>No Movies Yet.</li>
       {% endfor %}
    </ul>
    <p>
        Using https? 
        {{ request.is_secure|yesno }}
    </p>
</body>
</html> -->

django_project/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ object.first_name }}
  {{ object.last_name }}
{% endblock %}

{% block main %}
  <h1>{{ object }}</h1>
  <h2>Actor</h2>
  <ul>
      {% for role in object_set.all %}
      <li>
          <a href="{% url 'core:MovieDetail' role.movie.id %}">
              {{ role.movie }}
          </a>:
          {{ role.name }}
      </li>
      {% endfor %}
  </ul>
  <h2>Writer</h2>
  <ul>
     {% for movie on object.writing_credits.all %}
    <li>
       <a href="{% url 'core:MovieDetail' movie.id %}">
           {{ movie }}
       </a>
     </li>
      {% endfor %}
    </ul>
    <h2>Director</h2>
    <ul>
        {% for movie in object.directed.all %}
        <li>
            <a href="{% url 'core:MovieDetail' movie.id %}">
                {{ movie }}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}